version: 2
updates:
  - package-ecosystem: "pip" # This is covers pyproject.toml as well
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      otel:
        patterns:
          - "presidio-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
