"""Update empty provider endpoint names with placeholders

Revision ID: 736fb0c10480
Revises: e4c05d7591a8
Create Date: 2025-05-01 19:17:41.766575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "736fb0c10480"
down_revision: Union[str, None] = "e4c05d7591a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE provider_endpoints
        SET name = 'placeholder_' || id
        WHERE name = ''
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading is complex as we don't know which names were placeholders.
    # We'll leave this empty, assuming the model validation change is permanent.
    pass
    # ### end Alembic commands ###
