name: Create Documentation Issue (when needed) on PR Approval 

on:
  pull_request_review:
    types:
      - submitted

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Check PR Labels
        id: check-labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);

            if (!labels.includes('needs-docs')) {
              console.log('PR does not have the needs-docs label. Skipping issue creation.');
              core.setOutput('should_create_issue', 'false');
            } else {
              core.setOutput('should_create_issue', 'true');
            }

      - name: Create Issue in Documentation Repo
        if: steps.check-labels.outputs.should_create_issue == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repoOwner = 'stacklok';
            const repoName = 'codegate-docs';
            const pr = context.payload.pull_request;

            const issueTitle = `Docs update needed for PR #${pr.number}`;
            const issueBody = `A documentation update is needed for the following PR:\n\n${pr.html_url}\n\n**Summary:**\n${pr.title}`;

            github.rest.issues.create({
              owner: repoOwner,
              repo: repoName,
              title: issueTitle,
              body: issueBody,
              labels: ['documentation']
            });
