name: Automate Engineering Feature Release Campaigns

on:
  issues:
    types: [labeled]

jobs:
  notify-discord:
    if: github.event.label.name == 'feature-release'
    runs-on: ubuntu-latest
    steps:
      - name: Send Feature Release Notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          JSON_PAYLOAD=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" --arg url "$ISSUE_URL" \
          '{content: "**🚀 New Feature Incoming!**\n\n🎉 *\($title)* is now planned!\n📖 Description: \($body)\n🔗 [Check it out here](\($url))"}')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$JSON_PAYLOAD" \
          $DISCORD_WEBHOOK
