# These set of workflows run on every push to the main branch
name: Run - push_to_main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  security:
    name: Security Checks
    uses: ./.github/workflows/security.yml
  ci:
    name: Build, Test & Lint
    uses: ./.github/workflows/ci.yml
  image-build:
    name: OCI Image - Build x86
    uses: ./.github/workflows/image-build.yml
    with:
      artifact-name: "codegate-image"
      platform: "linux/amd64"
  image-build-arm64:
    name: OCI Image - Build ARM64
    uses: ./.github/workflows/image-build.yml
    with:
      artifact-name: "codegate-image"
      platform: "linux/arm64"
  integration-tests:
    name: Integration Tests
    needs: [ci, image-build] # We need the image available in order to run the integration tests
    uses: ./.github/workflows/integration-tests.yml
    with:
      artifact-name: "codegate-image"
    secrets:
      copilot-key: ${{ secrets.INTEGRATION_TESTS_COPILOT_KEY }}
      anthropic-key: ${{ secrets.INTEGRATION_TESTS_ANTHROPIC_KEY }}
      openrouter-key: ${{ secrets.INTEGRATION_TESTS_OPENROUTER_KEY }}      
  openapi:
    name: Generate the OpenAPI docs
    needs: [ci]
    uses: ./.github/workflows/openapi.yml
